import type { OfficePickCatalog } from "./types";

export const EN_CATALOG: OfficePickCatalog = {
  categories: [
    "Desk organization",
    "Sit-all-day saviors",
    "Desk vibes",
    "Stay-alive fuel",
  ],
  picks: [
    {
      id: "desk-organizer",
      category: "Desk organization",
      name: "Desktop drawer organizer",
      hook: "Cables, sticky notes, paper clips — finally a home. Step one of controlled chaos.",
      emoji: "🗂️",
      affiliateUrl: "https://u.jd.com/XawzbHn",
    },
    {
      id: "cable-box",
      category: "Desk organization",
      name: "Under-desk cable box / velcro ties",
      hook: "Dual-monitor lifeline — stop wrestling charging cables.",
      emoji: "🔌",
      affiliateUrl: "https://u.jd.com/X6wIehP",
    },
    {
      id: "monitor-stand",
      category: "Desk organization",
      name: "Monitor riser stand",
      hook: "Lift the screen, free space below — neck and desk both win.",
      emoji: "🖥️",
      affiliateUrl: "https://u.jd.com/X1wyucp",
    },
    {
      id: "lumbar-cushion",
      category: "Sit-all-day saviors",
      name: "Lumbar cushion / ergonomic seat pad",
      hook: "Your letter says you sit forever — your back says thanks.",
      emoji: "💺",
      affiliateUrl: "https://u.jd.com/X1wyucp",
    },
    {
      id: "wrist-rest",
      category: "Sit-all-day saviors",
      name: "Keyboard wrist rest + mouse pad",
      hook: "Mech keyboard plus soft rest — less wrist burnout.",
      emoji: "⌨️",
      affiliateUrl: "https://u.jd.com/X1wyucp",
    },
    {
      id: "desk-lamp",
      category: "Desk vibes",
      name: "Monitor light bar / warm desk lamp",
      hook: "Late nights without glare — photos look lived-in too.",
      emoji: "💡",
      affiliateUrl: "https://u.jd.com/X1wyucp",
    },
    {
      id: "desk-plant",
      category: "Desk vibes",
      name: "Low-maintenance desk plant",
      hook: "Replace that half-dead plant from your desk witness list.",
      emoji: "🪴",
      affiliateUrl: "https://u.jd.com/X1wyucp",
    },
    {
      id: "mug-warmer",
      category: "Stay-alive fuel",
      name: "Mug warmer",
      hook: "Cold coffee marks time at your desk — this keeps one sip hot.",
      emoji: "☕",
      affiliateUrl: "https://u.jd.com/X1wyucp",
    },
    {
      id: "instant-coffee",
      category: "Stay-alive fuel",
      name: "Pour-over / instant coffee packs",
      hook: "Stash a few in the drawer — 3 PM revival with your desk.",
      emoji: "🫘",
      affiliateUrl: "https://u.jd.com/X1wyucp",
    },
  ],
};
